name: Playwright Tests Demo
on:
  schedule:
    #run each Monday at 6am EST (11 am UTC)
    - cron: '0 11 * * 1'
<<<<<<< HEAD

  workflow_dispatch:
    inputs:
      testSuite:
=======
    
  workflow_dispatch:
    inputs:
      features:
>>>>>>> 03430f33975534975d8df743995b3da2523fa418
        description: 'Test suite to run'
        required: true
        default: 'regression'
        type: choice
        options:
<<<<<<< HEAD
          - smoke
          - regression

=======
          - regression
          - "--grep @smoke"
>>>>>>> 03430f33975534975d8df743995b3da2523fa418
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
    strategy:
      max-parallel: 6  # Adjust the number of parallel jobs as needed     
