name: Playwright Tests Demo
on:
  schedule:
    #run each Monday at 6am EST (11 am UTC)
    - cron: '0 11 * * 1'
    
  workflow_dispatch:
    inputs:
      features:
        description: 'Test suite to run'
        required: true
        default: 'regression'
        type: choice
        options:
          - regression
          - smoke
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
    
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 6  # Adjust the number of parallel jobs as needed     

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      run: |
        if [ "${{ github.event.inputs.features }}" == "smoke" ]; then
        npx playwright test --grep @smoke --workers=6
        else
        npx playwright test --workers=6
        fi

    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

